
/**
 * Constants
 * action types
 * 
 */
module.exports ={
    GET_CATEGORY_LIST:'GET_CATEGORY_LIST',
    GET_CATEGORY_LIST_SUCCESS:'GET_CATEGORY_LIST_SUCCESS',
    GET_CATEGORY_LIST_FAILED:'GET_CATEGORY_LIST_FAILED',

    GET_IMAGE_LIST:'GET_IMAGE_LIST',
    GET_IMAGE_LIST_SUCCESS:'GET_IMAGE_LIST_SUCCESS',
    GET_IMAGE_LIST_FAILED:'GET_IMAGE_LIST_FAILED'
}